name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - thorben.kuck@gmail.com
body:
  - type: markdown
    attributes:
      value: |
        We are sorry for your inconveniences. Thank you very much for taking the time to fill out this bug report! |
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please tell us, in the most precise language you can, what happened?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of WireDI are you running?
      options:
        - alpha-1
        - alpha-2
        - alpha-3
        - beta
        - V.1.0.0
    validations:
      required: true
  - type: textarea
    id: mcve
    attributes:
      label: Minimal, complete and verifiable example
      description: Please try to give us a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve), it helps a lot to debug the issue
      placeholder: Show us what you coded!
    validations:
      required: false
  - type: textarea
    id: root-cause
    attributes:
      label: Root cause
      description: If you know the root cause, please try to describe it as best as possible here. This can help us to fix the issue faster.
      placeholder: The issue occurs in ... when ... or ...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
